# Generated by Django 4.2.6 on 2024-11-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('about', models.CharField(max_length=250)),
                ('is_head', models.BooleanField(default=False)),
                ('is_core', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('about', models.CharField(max_length=250)),
                ('is_head', models.BooleanField(default=False)),
                ('is_core', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('about', models.CharField(max_length=250)),
                ('is_head', models.BooleanField(default=False)),
                ('is_core', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
