# Generated by Django 4.2.6 on 2024-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementteam',
            name='about',
            field=models.CharField(default='Team Member', max_length=250),
        ),
        migrations.AlterField(
            model_name='managementteam',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile_image.jpg', null=True, upload_to='teams/'),
        ),
        migrations.AlterField(
            model_name='marketingteam',
            name='about',
            field=models.CharField(default='Team Member', max_length=250),
        ),
        migrations.AlterField(
            model_name='marketingteam',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile_image.jpg', null=True, upload_to='teams/'),
        ),
        migrations.AlterField(
            model_name='techteam',
            name='about',
            field=models.CharField(default='Team Member', max_length=250),
        ),
        migrations.AlterField(
            model_name='techteam',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile_image.jpg', null=True, upload_to='teams/'),
        ),
    ]
