# Generated by Django 4.2.6 on 2024-11-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_managementteam_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementteam',
            name='about',
            field=models.CharField(blank=True, default='Team Member', max_length=250),
        ),
        migrations.AlterField(
            model_name='marketingteam',
            name='about',
            field=models.CharField(blank=True, default='Team Member', max_length=250),
        ),
        migrations.AlterField(
            model_name='techteam',
            name='about',
            field=models.CharField(blank=True, default='Team Member', max_length=250),
        ),
    ]
