# Generated by Django 4.2.6 on 2024-11-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_managementteam_about_alter_marketingteam_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementteam',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketingteam',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='techteam',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='managementteam',
            name='profile_image',
            field=models.ImageField(blank=True, default='/default_profile_image.jpg', null=True, upload_to='teams/'),
        ),
        migrations.AlterField(
            model_name='marketingteam',
            name='profile_image',
            field=models.ImageField(blank=True, default='/default_profile_image.jpg', null=True, upload_to='teams/'),
        ),
        migrations.AlterField(
            model_name='techteam',
            name='profile_image',
            field=models.ImageField(blank=True, default='/default_profile_image.jpg', null=True, upload_to='teams/'),
        ),
    ]
