# Generated by Django 4.2.6 on 2024-11-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_managementteam_drive_file_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, default='/default_profile_image.jpg', null=True, upload_to='teams/')),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.CharField(blank=True, default='Team Member', max_length=250)),
                ('is_head', models.BooleanField(default=False)),
                ('is_core', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, default='/default_profile_image.jpg', null=True, upload_to='teams/')),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.CharField(blank=True, default='Team Member', max_length=250)),
                ('is_head', models.BooleanField(default=False)),
                ('is_core', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
