# Generated by Django 4.2.6 on 2024-10-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('domain', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(upload_to='events/')),
                ('registeration_fees', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
