# Generated by Django 4.2.6 on 2024-11-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_status_alter_eventsregistered_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
