# Generated by Django 4.2.6 on 2024-11-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_drive_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
